TEAM-Hearus/HEARUS-REACT-FRONTEND

src/components/common/TimeTableItem/TimeTableItem.module.scss, src/components/common/TimeTableItem/TimeTableItem.tsx, src/constants/colors.ts, src/pages/Main/TimeTable/MonthlyTimeTable/MonthlyTimeTable.tsx, src/pages/Main/TimeTable/TimeTable.module.scss, src/pages/Main/TimeTable/TimeTable.tsx, src/pages/Main/TimeTable/WeeklyTimeTable/WeeklyTimeTable.module.scss, src/pages/Main/TimeTable/WeeklyTimeTable/WeeklyTimeTable.tsx, src/pages/index.tsx, src/styles/variables/fonts.scss, src/utils/randomColor.ts, src/utils/schedule.ts
schedule page 디자인 변경
랜덤 컬러 추가 
월간페이지 삭제 
schedule page 디자인 표테이블 모양으로 변경
랜덤 컬러 추가 - backgorund color, text color 함수 추가 및 랜덤 부여 **( 나중에 db컬럼 추가시 과목별 색상 부여 추가 예정)**
과목별 item 크기별로 나타나게 수정 **-(강의 시간은 확실하지 않아서 지우지 않았습니다.)**
월간페이지 삭제 - router 수정
폰트 pt -> px로 수정
=> Design/schedule page 디자인 변경, 랜덤컬러 추가, 월간페이지 삭제

src/components/common/TimeTableItem/TimeTableItem.tsx, src/pages/Main/TimeTable/TimeTable.module.scss, src/pages/Main/TimeTable/WeeklyTimeTable/WeeklyTimeTable.module.scss
사이즈별 제목, 시간 표기 조정
양옆 사이즈 조정 
사이즈별 제목, 시간 표기 조정
양옆 사이즈 조정
=> design: 크기별 시간제목 조정 및 css수정

src/apis/auth.ts, src/apis/index.ts, src/apis/schedule.ts, src/apis/script.ts, src/pages/Auth/AuthForm/AuthForm.module.scss, src/pages/Auth/AuthForm/AuthForm.tsx, src/pages/Auth/AuthForm/Login.tsx, src/pages/Auth/AuthForm/SignUp.tsx, src/pages/Main/MyScript/MyScript.tsx
회원가입, 로그인 오류 해결
- loginMutation, signupMutation 변수를 따로 생성
- 입력 값 중 하나 이상이 공백이면 return으로 종료
- 회원가입 폼에 이름 입력 란 추가
- 삼항연산자가 false일때 아무것도 나타나지 않게 하고싶을때는 삼항연산자보다는 && 연산자를 쓰는게 더 간결합니다. 
따라서 삼항연산자 `booleanValue ? element : <></>` 이런식으로 되어있던 것들은 `booleanValue && element`로 변경했습니다.
=> Fix: 회원가입, 로그인 오류 해결

src/apis/script.ts, src/components/atoms/HighlightedText/HighlightedText.module.scss, src/components/atoms/HighlightedText/HighlightedText.tsx, src/components/molecules/ScriptItem/ScriptItem.tsx, src/components/templates/modals/ScriptDetailModal/ScriptDetailModal.module.scss, src/components/templates/modals/ScriptDetailModal/ScriptDetailModal.tsx
스크립트 하이라이트 및 상세 모달에서 태그 표시
- `HighlightedText` 컴포넌트 생성: 하이라이트 여부에 따라 하이라이트 처리하는 글씨 컴포넌트
- 상세 모달에서 재생바 제거하고 태그 표시
=> Feat: 스크립트 하이라이트 및 상세 모달에서 태그 표시

src/apis/test.ts, src/components/molecules/questions/MultipleChoice/MultipleChoice.tsx, src/components/organisms/headers/TestHeader/TestHeader.tsx, src/constants/question.ts, src/pages/Main/TestMake/TestMake.tsx, src/pages/Test/Test.tsx, src/store/useTestSettingsStore.ts
문제 생성 API 연결
- 문제 더미데이터 제거하고 실제 API 연결
- 문제 유효성 검사: 문제 옵션 선택할때 빠져있는 옵션 있으면 alert로 알림
=> Feat: 문제 생성 API 연결

src/components/molecules/ScriptToolTip/ScriptToolTip.tsx
시간표 삭제 invalidateQuries에 userName 할당
=> Fix: invalidateQueries에 시간표 삭제할때 userName 할당

src/apis/auth.ts, src/pages/Auth/AuthForm/AuthForm.tsx, src/pages/Auth/OAuthCallback.tsx
카카오 로그인 추가
-  IGoogleLoginParams -> ISocialLoginParams로 이름 변경 
-  googleLogin -> OAuthLogin으로 이름 변경 
-  social 추가하여 google, kakao를 parameter로 받게 변경 
네이버 로고 추가되면 네이버 붙일 예정!
=> feat: 카카오 로그인 추가

src/components/organisms/headers/RecordHeader/Recordheader.module.scss, src/components/organisms/headers/TestHeader/TestHeader.module.scss
녹음, 문제풀이 헤더에서 width: 100dvw 제거
=> design: 녹음, 문제풀이 헤더에서 width: 100dvw 제거

src/components/organisms/headers/RecordHeader/Recordheader.module.scss, src/components/organisms/headers/TestHeader/TestHeader.module.scss, src/hooks/useOutsideClick.ts, src/pages/Main/Mypage/ProfileEdit/ProfileEdit.tsx, src/pages/Main/TimeTable/TimeTable.tsx, src/pages/Record/Record.module.scss, src/pages/Record/Record.tsx
강의 추가 폼 외부 클릭하면 닫히게 수정, 녹음 자막 표시
- `useOutsideClick` 커스텀 훅 생성
- 현재 녹음 자막 표시
- 보고서에도 추가 작성해야할 것 같습니다.
=> Feat: 강의 추가 폼 외부 클릭하면 닫히게 수정 및 현재 자막 표시

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, src/hooks/useRecorder.ts, src/pages/Auth/AuthForm/AuthForm.module.scss, src/pages/Main/Mypage/Mypage.tsx, src/pages/Main/TestMake/TestMake.module.scss, src/pages/Test/Test.module.scss, src/pages/Test/Test.tsx
스크립트 아이템 너비 수정, 문제 페이지 조건 및 로딩바 너비 수정
=> Fix: 스크립트 아이템 너비 수정, 문제 페이지 조건 및 로딩바 너비 수정

src/pages/Record/Record.module.scss
=> design: 자막 디자인 수정

src/pages/Auth/AuthForm/AuthForm.module.scss, src/pages/Landing/Landing.module.scss
=> Fix: 랜딩페이지 가로스크롤 방지

src/pages/Auth/AuthForm/AuthForm.module.scss, src/pages/Auth/AuthForm/AuthForm.tsx
Reverts TEAM-Hearus/HEARUS-REACT-FRONTEND#74
=> Revert "feat: 회원가입 유효성 검사 추가"

src/apis/auth.ts, src/pages/Auth/OAuthCallback.tsx
소셜 로그인 callback path 수정 및 인코딩 추가
callback에서 pathname에 배열 잘못 가져오고 있어서 수정 및 인코딩 추가
=> fix: 소셜로그인 인코딩 및 callback path 수정

src/pages/Main/Mypage/Mypage.tsx, src/pages/Main/Mypage/ProfileEdit/ProfileEdit.tsx, src/pages/Main/Mypage/ProfileView/ProfileView.tsx
=> Fix:mapage  이미지 삭제

src/App.tsx, src/components/organisms/headers/TestHeader/TestHeader.tsx, src/components/templates/modals/RecordModal/RecordModal.module.scss, src/components/templates/modals/RecordModal/RecordModal.tsx, src/hooks/useRecorder.ts, src/pages/Record/Record.module.scss, src/pages/Test/Test.tsx
문제 종료 모달 버그 및 window에서 포커스 나가면 refetch되는 버그 해결
- queryClient: refetchOnWindowFocus: false 조건 추가
- isFetching일때 문제 종료 모달 안열리게 처리
- 스크립트 저장시 인공지능 가공 처리 대기 상태 추가
=> Fix: 문제 종료 모달 버그 및 window에서 포커스 나가면 refetch되는 버그 해결

src/components/organisms/AddScheduleForm/AddScheduleForm.module.scss, src/components/organisms/AddScheduleForm/AddScheduleForm.tsx, src/pages/Main/TimeTable/TimeTable.module.scss
시간표 이름 중복 토스트
- 중복된 강의 제목 추가할 경우 토스트 알림
- 중복된 강의 처리 방법 안내 문구 추가
=> feat: 시간표 이름 중복 토스트

src/hooks/useUserInfo.ts, src/pages/Main/Mypage/Mypage.tsx
=> fix: 학년 표시 수정

src/constants/landing.ts, src/pages/Landing/Landing.tsx
Pretendard 라이선스 명시 및 대표자 연락처 수정
- 라이선스 고지 페이지에 Pretendard 정보 추가
- 랜딩페이지 대표자 연락처 수정
=> Chore: Pretendard 라이선스 명시 및 대표자 연락처 수정

src/pages/Main/MyScript/MyScript.tsx, src/pages/Main/TestMake/TestMake.tsx
인공지능 기능 이용 불가 안내
- 녹음 시작, 테스트 시작 버튼 누르면 `현재 인공지능 기능은 이용 불가합니다.` 토스트 띄우기
- 추후 기능 재개시 주석 해제 필요
- `src/pages/Main/TestMake/TestMake.tsx`
- `src/pages/Main/MyScript/MyScript.tsx`
=> Chore: 인공지능 기능 이용 불가 안내
